kind: pipline
name: Winsper-Zuul

steps:
  - name: test
    image: maven
    volumes:
      - name: dependency
        path: /root/.m2
    # - name: configuration
    #   path: /drone/src/back-end/src/main/resources/application.yml
    commands:
      - mvn clean
      - mvn package -Dmaven.test.skip=true
      - echo "test and package zuul completed 🙂🙂🙂"

  - name: upload_master
    image: appleboy/drone-scp
    settings:
      host: 10.0.0.98
      username: root
      rm: true
      target: /Winsper/winsper-zuul
      source:
        - target/winsper-zuul-0.0.1-SNAPSHOT.jar
        - Dockerfile

  - name: make_image_and_deploy_master
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.98
      username: root
      script:
        - cd /Winsper/winsper-zuul/target
        - cp ../Dockerfile .
        - docker build -t winsper-zuul .
        - docker rm -f winsper-zuul-c
        - docker run -d --name winsper-zuul-c --expose=30527 -p 30527:30527 -e "EUREKA_INSTANCE_IP-ADDRESS=10.0.0.98" -e "SERVER_PORT=30527" winsper-zuul

volumes:
  - name: dependency
    host:
      path: /root/.m2